[package]
name = "pandemist_vehicle_elements"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lotus-script = "0.4.1"
glam = "0.28.0"
